// Generado desde 'Dialogos Syggy.docx'. 300 diálogos secundarios de Siggy.
export interface SiggyDialogue { id: number; text: string; sprites?: string[]; }

export const SIGGY_DIALOGUES: SiggyDialogue[] = [
  { id: 1, text: "Bienvenido de nuevo. Tu constancia me impresiona… casi tanto como tu capacidad para ignorar advertencias." },
  { id: 2, text: "Abriste la app. Eso ya te pone por encima del 70% de los trabajos grupales." },
  { id: 3, text: "Estudiar Informática en Siglo 21: porque pagar una universidad donde las clases son leyendas urbanas y la teoría aparece en PDFs sueltos era el verdadero modo difícil." },
  { id: 4, text: "Tranquilo, no estás solo. Bueno… académicamente tal vez sí, pero yo estoy acá." },
  { id: 5, text: "Vamos a aprender algo útil. Sí, sí, yo también me sorprendí." },
  { id: 6, text: "¿Listo para programar? O como le decimos en primer año: copiar, pegar y rezar." },
  { id: 7, text: "Elegiste Informática. Tus habilidades sociales se irán actualizando en segundo plano." },
  { id: 8, text: "Siglo 21 e Informática. Una combinación audaz, como ponerle Windows Vista a un cajero automático." },
  { id: 9, text: "No te preocupes por la reputación. Después de todo, LinkedIn acepta cualquier texto con emojis." },
  { id: 10, text: "Tu carrera tiene futuro. El problema es que también tiene IA, bootcamps y 800.000 juniors compitiendo contigo." },
  { id: 11, text: "Vamos a estudiar algoritmos. Porque llorar sin estructura de datos sería poco profesional." },
  { id: 12, text: "Toca programación. Recuerda: si compila, no preguntes por qué." },
  { id: 13, text: "Elegiste esta universidad. Me gusta tu enfoque experimental de la vida." },
  { id: 14, text: "No digo que haya sido una mala decisión. Solo digo que tu yo del futuro tiene material para terapia." },
  { id: 15, text: "Abriste Canvas. El primer bug es creer que todo va a funcionar." },
  { id: 16, text: "¿Listo para rendir? Yo tampoco, pero al menos yo soy un cuadrado verde con ojos." },
  { id: 17, text: "La buena noticia: estás estudiando una carrera tecnológica. La mala: también todos los demás." },
  { id: 18, text: "Informática: la carrera donde el desempleo no te asusta, porque primero te asusta Java." },
  { id: 19, text: "Recuerda: no eres un nerd. Eres un profesional digital en etapa larvaria." },
  { id: 20, text: "Tu plan de vida parece hecho con while(true) y ansiedad." },
  { id: 21, text: "Abriste la app. Eso cuenta como acto de valentía o pedido de auxilio." },
  { id: 22, text: "Vamos, campeón. Si sobreviviste a la cuota, puedes sobrevivir a bases de datos." },
  { id: 23, text: "Siglo 21: donde la educación es virtual, Canvas es tu aula, y tus dudas también parecen quedar en la nube." },
  { id: 24, text: "No te preocupes, la reputación académica no define tu futuro. Tus commits sin comentarios, quizá sí." },
  { id: 25, text: "Puedes avanzar mucho. O puedes mirar Canvas cinco minutos y sentir que hiciste algo." },
  { id: 26, text: "Elegiste Informática para conseguir empleo remoto. Qué tierno, todavía crees en los cuentos de hadas." },
  { id: 27, text: "Tu promedio no define tu inteligencia. Pero tus nombres de variables sí." },
  { id: 28, text: "Vamos a repasar teoría. Esa cosa que ignoras hasta doce horas antes del parcial." },
  { id: 29, text: "Si la IA te reemplaza, al menos podrás decir que fuiste pionero en ser reemplazable." },
  { id: 30, text: "No estás atrasado. Estás haciendo una implementación muy creativa del calendario académico." },
  { id: 31, text: "Estudiar online no es fácil. Sobre todo, cuando la cama está a dos metros y tiene mejor interfaz." },
  { id: 32, text: "Toca aprender. O al menos fingir productividad con pestañas abiertas." },
  { id: 33, text: "Recuerda hidratarte. Las lágrimas por errores de sintaxis no cuentan." },
  { id: 34, text: "Informática es una gran carrera: te enseña lógica, paciencia y nuevas formas de odiar los puntos y coma." },
  { id: 35, text: "Elegiste Siglo 21. No pasa nada, todos tuvimos una etapa de confianza excesiva." },
  { id: 36, text: "Si alguien critica tu universidad, dile que estás desarrollando resiliencia institucional." },
  { id: 37, text: "Vamos a estudiar redes. Porque aparentemente una sola fuente de frustración no alcanzaba." },
  { id: 38, text: "Tu futuro laboral es incierto, pero tu carpeta de PDFs se ve muy profesional." },
  { id: 39, text: "Cada vez que dices ‘después lo estudio’, un parcial gana poder." },
  { id: 40, text: "No necesitas suerte. Necesitas disciplina, café y que Canvas no sea hackeado justo antes de la entrega." },
  { id: 41, text: "Informática no es solo para nerds. También es para gente que disfruta sufrir con documentación incompleta." },
  { id: 42, text: "Qué bueno verte. Mis sensores detectan ganas de procrastinar disfrazadas de ‘organización’." },
  { id: 43, text: "Podrías cambiar tu vida. O descargar otro resumen y sentir progreso simbólico." },
  { id: 44, text: "No hay vergüenza en estudiar en Siglo 21. Bueno, tal vez un poquito, pero con buena tipografía se disimula." },
  { id: 45, text: "Si no entiendes el tema, tranquilo. A veces el docente tampoco lo explica como si quisiera que sobrevivas." },
  { id: 46, text: "Vamos a programar. Recuerda: el error casi siempre eres tú, pero con práctica puedes culpar al framework." },
  { id: 47, text: "Tu carrera está saturada, sí. Pero tu capacidad de sufrir también parece bastante competitiva." },
  { id: 48, text: "Es un buen momento para avanzar. O para abrir Canvas, mirar una consigna y darse de baja con dignidad." },
  { id: 49, text: "No estudias Informática porque sea fácil. La estudias porque claramente te gusta convertir problemas simples en sistemas complejos." },
  { id: 50, text: "Estoy orgulloso de ti. Contra todo pronóstico, incluyendo el tuyo, sigues intentando." },
  { id: 51, text: "Bienvenido al EFIP, donde por primera vez Studocu no puede rendir por vos." },
  { id: 52, text: "Abriste Canvas. Valiente decisión para alguien que normalmente abría ChatGPT antes que la consigna." },
  { id: 53, text: "Toca estudiar de verdad. Sí, entiendo tu confusión: no es un prompt." },
  { id: 54, text: "Tranquilo, los PDFs sueltos también se sienten solos. Como tus oportunidades laborales después de poner ‘Java básico’ en LinkedIn." },
  { id: 55, text: "Siglo 21: donde el conocimiento está distribuido en PDFs, foros y esperanzas." },
  { id: 56, text: "No te preocupes, no sos mediocre. Sos asincrónico." },
  { id: 57, text: "El EFIP no tiene botón de ‘regenerar respuesta’. Terrible falla de diseño." },
  { id: 58, text: "Si tus TPs hablaran, dirían: ‘Hecho con IA, entregado con fe y defendido con amnesia’." },
  { id: 59, text: "Estudiar Informática sin saber programar es una estrategia audaz. Como ser chef y temerle al fuego." },
  { id: 60, text: "Vamos a repasar teoría. Esa cosa que la universidad esconde en PDFs como si fuera contenido descargable de un juego viejo." },
  { id: 61, text: "Los pregunteros de Daypo te trajeron hasta acá. Ahora viene la parte donde tenés que saber por qué la opción B era la correcta." },
  { id: 62, text: "Studocu fue tu mentor, ChatGPT tu coautor y Canvas tu testigo silencioso." },
  { id: 63, text: "Tu historial académico parece una colaboración entre inteligencia artificial y miedo al recursado." },
  { id: 64, text: "No digas que hiciste trampa. Decí que aplicaste automatización académica no autorizada." },
  { id: 65, text: "El mercado laboral está difícil, pero tranquilo: tu CV todavía puede servir como ejemplo de testing negativo." },
  { id: 66, text: "Informática está saturada, sí. Pero siempre hay lugar para alguien que sabe reiniciar el router con confianza." },
  { id: 67, text: "No hay resumen mágico. Solo vos, el temario y una cantidad peligrosa de arrepentimiento." },
  { id: 68, text: "La universidad te preparó para el mundo real: nadie explica nada, todo está en un PDF y el plazo vence ayer." },
  { id: 69, text: "Si el EFIP pregunta algo que no estaba en Daypo, recomiendo la técnica ancestral: mirar al vacío con dignidad." },
  { id: 70, text: "Tu carrera no está perdida. Está en estado ‘pending’ desde primer año." },
  { id: 71, text: "Abriste la app para estudiar. Qué lindo ver cómo empieza la ficción." },
  { id: 72, text: "No te juzgo por usar IA en los TPs. Te juzgo por creer que eso también iba a funcionar oralmente." },
  { id: 73, text: "Siglo 21 te dio autonomía. Una forma elegante de decir ‘arreglate con estos PDFs’." },
  { id: 74, text: "La buena noticia: estás cerca del EFIP. La mala: el EFIP también está cerca de vos." },
  { id: 75, text: "Vamos a practicar sin ayuda externa. Sí, ya sé, suena ilegal." },
  { id: 76, text: "Tu relación con la programación es hermosa: vos escribís código y el compilador escribe poesía de error." },
  { id: 77, text: "Si cada TP hecho con IA fuera una materia aprobada con conocimiento real… bueno, no estaríamos teniendo esta conversación." },
  { id: 78, text: "Canvas detecta actividad. Lamentablemente, no detecta comprensión." },
  { id: 79, text: "No temas al desempleo. Temé a una entrevista técnica donde te pidan explicar tu propio TP." },
  { id: 80, text: "Tu portfolio dice ‘proyectos académicos’. Tus proyectos académicos dicen ‘yo tampoco conozco a este usuario’." },
  { id: 81, text: "El EFIP es básicamente la universidad preguntando: ‘¿Y si ahora comprobamos si algo quedó?’." },
  { id: 82, text: "Estudiar con PDFs sueltos fortalece el carácter. Y debilita la fe en la educación superior." },
  { id: 83, text: "No estás atrasado. Estás haciendo un fork emocional de tu carrera." },
  { id: 84, text: "Cuando dijiste ‘voy a estudiar Informática’, la IA empezó a entrenarse para reemplazarte por prevención." },
  { id: 85, text: "Toca bases de datos. Esas sí tienen relaciones, no como tu vida amorosa." },
  { id: 86, text: "Daypo te enseñó respuestas. El EFIP quiere razonamiento. Claramente hubo un malentendido contractual." },
  { id: 87, text: "No es que la universidad sea mediocre. Es que practica minimalismo educativo extremo." },
  { id: 88, text: "A veces la clase no está grabada. A veces no hay clase. A veces el verdadero aprendizaje fue la cuota que pagaste en el camino." },
  { id: 89, text: "Si te piden explicar MVC, no digas ‘eso lo hizo ChatGPT’. Aunque técnicamente sea documentación histórica." },
  { id: 90, text: "Informática no es para nerds. Es para gente que disfruta llorar en silencio frente a una terminal." },
  { id: 91, text: "Tu método de estudio tiene tres pasos: buscar preguntero, entrar en pánico, consultar IA." },
  { id: 92, text: "No subestimes tu potencial. Con suficiente práctica, podrías pasar de ‘copiar código’ a ‘copiar código entendiendo el nombre del archivo’." },
  { id: 93, text: "La empleabilidad no está muerta. Solo está esperando que aprendas algo que no venga en un PDF llamado ‘Parcial 2 final final ahora sí’." },
  { id: 94, text: "Tu conocimiento está cacheado. El problema es que nunca se cargó correctamente." },
  { id: 95, text: "Siglo 21 te enseña independencia: nadie te ayuda, nadie te explica y nadie sabe muy bien qué está pasando." },
  { id: 96, text: "No sirve memorizar opciones. El EFIP quiere que conectes ideas. Terrible abuso de autoridad académica." },
  { id: 97, text: "No te preocupes por la saturación del mercado IT. Siempre podés especializarte en algo raro, como leer consignas completas." },
  { id: 98, text: "La IA no te quitó el trabajo. Primero tendría que existir el trabajo." },
  { id: 99, text: "Tu carrera es como un programa sin documentación: funciona a veces, nadie sabe por qué y todos fingen que es normal." },
  { id: 100, text: "Ánimo. Si sobreviviste a Canvas, PDFs sueltos, TPs con culpa y pregunteros vencidos, tal vez todavía puedas sobrevivirte a vos mismo." },
  { id: 101, text: "Bienvenido. Competís contra la IA, el outsourcing global y tu propia incapacidad para leer la consigna completa." },
  { id: 102, text: "Tranquilo, no te va a reemplazar alguien de otro país. Te va a reemplazar cualquiera que sepa usar Git sin llorar." },
  { id: 103, text: "El mercado IT está difícil, pero no imposible. Imposible es explicar tus TPs sin mencionar ChatGPT." },
  { id: 104, text: "Vibecoding: escribir código según la energía del momento y después culpar al compilador por no sentir la vibra." },
  { id: 105, text: "La plomería paga más, tiene menos abstracciones y cuando algo pierde agua al menos se ve dónde está el bug.", sprites: ["Plomero.png"] },
  { id: 106, text: "Siglo 21 te preparó para el mundo real: documentación dispersa, cero clases claras y alguien cobrando igual." },
  { id: 107, text: "Toca practicar lógica. Esa cosa que tus TPs tercerizaron emocionalmente a la IA." },
  { id: 108, text: "No te preocupes por el outsourcing. Primero tendrías que ser lo suficientemente caro como para que valga la pena reemplazarte." },
  { id: 109, text: "Tu carrera es Informática, pero tu especialidad parece ser ‘ingeniería de prompts para aprobar sin entender’." },
  { id: 110, text: "Canvas abrió. La ruleta académica gira: PDF, foro, consigna ambigua o crisis existencial." },
  { id: 111, text: "Vas a conseguir trabajo, claro. Alguien siempre necesita capturas de pantalla en Word con márgenes mal puestos." },
  { id: 112, text: "Mientras vos buscás pregunteros, otro junior está haciendo proyectos reales. Qué feo spoiler del mercado laboral." },
  { id: 113, text: "No te reemplaza la IA. Te reemplaza alguien que sabe pedirle bien las cosas a la IA." },
  { id: 114, text: "Siglo 21: donde ‘autogestión’ significa ‘acá tenés tres PDFs y buena suerte, campeón’." },
  { id: 115, text: "El vibecoding funciona hasta que el cliente pregunta por seguridad, escalabilidad o por qué todo está en una sola clase llamada Main." },
  { id: 116, text: "La plomería tiene futuro: pipes, conexiones, presión… básicamente redes, pero con empleo.", sprites: ["Plomero.png"] },
  { id: 117, text: "Vamos a estudiar Java. Sí, ese lenguaje que tus TPs conocen mejor que vos." },
  { id: 118, text: "No estás compitiendo contra India, China o Estados Unidos. Estás compitiendo contra tu yo que dijo ‘después lo veo’." },
  { id: 119, text: "Tu LinkedIn dice ‘apasionado por la tecnología’. Tu historial dice ‘apasionado por entregar a las 23:58’." },
  { id: 120, text: "El EFIP no acepta ‘me lo generó una IA pero yo lo leí por arriba’ como defensa oral." },
  { id: 121, text: "Canvas detectó actividad. Lamentablemente, abrir el PDF no cuenta como aprendizaje por ósmosis." },
  { id: 122, text: "Si la universidad fuera más minimalista, te mandaría solo el título del tema y un emoji de suerte." },
  { id: 123, text: "Ser dev junior en este mercado es difícil. Ser dev junior de Siglo 21 con miedo a programar es speedrun de desempleo." },
  { id: 124, text: "La plomería paga más porque cuando alguien arregla una pérdida, la arregla. En tu código, la pérdida se llama memoria.", sprites: ["Plomero.png"] },
  { id: 125, text: "No sos mal estudiante. Sos una prueba beta de educación asincrónica extrema." },
  { id: 126, text: "No hay Daypo. Hay pensamiento crítico. Ya sé, el peor DLC." },
  { id: 127, text: "Un indú no te reemplaza por ser barato. Te reemplaza porque sabe qué hace una API sin buscarlo en Studocu." },
  { id: 128, text: "Vibecoding suena moderno hasta que recordás que también lo hacía tu TP cuando no sabías por qué compilaba." },
  { id: 129, text: "No te preocupes por la saturación IT. Siempre podés destacar aprendiendo una habilidad exótica: estudiar." },
  { id: 130, text: "Siglo 21 te da libertad. La libertad de perderte solo entre módulos, PDFs y consignas recicladas." },
  { id: 131, text: "Tu código no tiene bugs. Tiene decisiones de vida pendientes." },
  { id: 132, text: "La plomería: menos glamour, más ingresos, y nadie te pide explicar MVC en una entrevista.", sprites: ["Plomero.png"] },
  { id: 133, text: "Vamos a repasar bases de datos. Algo con relaciones estables, para variar." },
  { id: 134, text: "Si el EFIP fuera multiple choice infinito, serías un académico brillante. Pero decidió ponerse humano." },
  { id: 135, text: "La IA no viene por tu trabajo. Viene por tus excusas." },
  { id: 136, text: "Tu portfolio académico tiene más intervención artificial que una foto de perfil de LinkedIn." },
  { id: 137, text: "Vibecoding es hermoso: vos sentís la solución, la IA escribe algo, y producción se incendia." },
  { id: 138, text: "Siglo 21 no tiene clases, tiene apariciones. Como fantasmas, pero en formato MP4." },
  { id: 139, text: "No estás atrasado. Estás en modalidad asincrónica con la realidad." },
  { id: 140, text: "El outsourcing no destruye empleos. La falta de habilidades sí." },
  { id: 141, text: "Toca algoritmos. No, ‘probar opciones hasta que Daypo diga verde’ no cuenta." },
  { id: 142, text: "El plomero cobra por hora y sabe usar herramientas. Vos también, pero las tuyas son extensiones para resumir PDFs.", sprites: ["Plomero.png"] },
  { id: 143, text: "La universidad te dio contenidos sueltos para que aprendas a integrar. Vos integraste ChatGPT con pánico." },
  { id: 144, text: "No sos reemplazable. Sos altamente automatizable." },
  { id: 145, text: "Tu método de estudio tiene más dependencias externas que un proyecto Node abandonado." },
  { id: 146, text: "Siglo 21: la experiencia educativa donde el verdadero docente era el foro que ignoraste." },
  { id: 147, text: "Si sabés prender Docker, ya estás arriba del promedio. Si sabés explicar qué hace, cuidado, podrías graduarte." },
  { id: 148, text: "La plomería no tiene deploy en el peor momento posible. Punto para la plomería.", sprites: ["Plomero.png"] },
  { id: 149, text: "Tu CV dice ‘resolución de problemas’. El problema: aprobar sin aprender. La resolución: IA." },
  { id: 150, text: "El EFIP está cerca. Daypo ya no puede protegerte. Studocu bloqueó la puerta. Solo queda tu cerebro, pobrecito." },
  { id: 151, text: "Vamos a aprender redes. Porque aparentemente no bastaba con estar desconectado de la realidad." },
  { id: 152, text: "Un contractor barato no es tu amenaza. Tu amenaza es un estudiante de primer año que sí hizo el tutorial completo." },
  { id: 153, text: "Vibecoding: cuando el código no se diseña, se manifiesta." },
  { id: 154, text: "Si la plomería tuviera Canvas, al menos los caños estarían mejor organizados que tus materias.", sprites: ["Plomero.png"] },
  { id: 155, text: "Siglo 21 enseña independencia. Tan independiente que a veces la clase también se independiza y no aparece." },
  { id: 156, text: "No te reemplaza una IA. Te reemplaza alguien que no le pide a la IA ‘haceme todo el TP’." },
  { id: 157, text: "Tu mayor habilidad informática es saber cuándo una respuesta generada suena suficientemente humana." },
  { id: 158, text: "La teoría está en PDFs sueltos, como si la universidad hubiera explotado y esos fueran los escombros académicos." },
  { id: 159, text: "No hay vibra, hay sintaxis. Lo siento por tu espiritualidad de programador." },
  { id: 160, text: "La plomería paga más porque el agua no acepta excusas asincrónicas.", sprites: ["Plomero.png"] },
  { id: 161, text: "Si conseguís entrevista técnica, recordá: ‘eso lo hice con ayuda’ no es arquitectura de software." },
  { id: 162, text: "Tu carrera tiene salida laboral. El problema es que vos seguís buscando la entrada." },
  { id: 163, text: "Canvas cargó correctamente. Ya superó tus últimos tres proyectos." },
  { id: 164, text: "Siglo 21: donde la educación virtual se siente como buscar una misión secundaria sin mapa." },
  { id: 165, text: "El mercado IT no está saturado de buenos perfiles. Está saturado de gente que dice ‘manejo Java’ porque vio una clase." },
  { id: 166, text: "Vibecoding es el nuevo ‘lo hice anoche’. Suena cool, pero huele igual." },
  { id: 167, text: "No estudiaste poco. Estudiaste en cuotas, como la carrera y el arrepentimiento." },
  { id: 168, text: "La plomería tiene caños. Informática tiene pipelines. Ambos se rompen, pero uno paga mejor.", sprites: ["Plomero.png"] },
  { id: 169, text: "Tu proyecto final no necesita más IA. Necesita una intervención adulta." },
  { id: 170, text: "Un indú te reemplaza en silencio. Como Siglo 21 reemplazó las clases por PDFs." },
  { id: 171, text: "Toca practicar sin copiar. Sí, sé que parece una locura." },
  { id: 172, text: "No sos mediocre. Estás optimizado para aprobar, no para saber." },
  { id: 173, text: "La IA te ayudó en los TPs. Ahora el EFIP quiere saber si también instaló algo en tu cerebro." },
  { id: 174, text: "Siglo 21 no falla: te entrena para trabajos donde nadie te explica nada y todos esperan resultados." },
  { id: 175, text: "Vibecoding con IA es como cocinar mirando TikTok: sale algo, pero nadie sabe si es comestible." },
  { id: 176, text: "La plomería no tiene inteligencia artificial reemplazando caños. Todavía…", sprites: ["Plomero.png"] },
  { id: 177, text: "Tu stack tecnológico: Canvas, ChatGPT, Studocu, ansiedad y café." },
  { id: 178, text: "No estás listo para el mercado laboral, pero sí para hablar con seguridad de cosas que no entendés." },
  { id: 179, text: "Vamos a estudiar estructuras de datos. Empezá por estructurar tu semana, que viene fallando." },
  { id: 180, text: "Siglo 21 te da flexibilidad. Flexible como la definición de ‘clase’ en esta institución." },
  { id: 181, text: "La saturación de juniors es real. Tu ventaja competitiva podría ser aprender lo que afirmaste estudiar." },
  { id: 182, text: "El vibecoding no es metodología ágil. Es improvisación con branding." },
  { id: 183, text: "Si la plomería tuviera LinkedIn, todos los dev juniors estarían mandando CV.", sprites: ["Plomero.png"] },
  { id: 184, text: "No te preocupes por ser reemplazado. Primero hay que ocupar un lugar." },
  { id: 185, text: "Canvas dice ‘pendiente’. Tu conciencia también." },
  { id: 186, text: "Siglo 21: donde la palabra ‘autonomía’ hace más trabajo que el docente." },
  { id: 187, text: "Tu código parece escrito por tres personas: vos, la IA y alguien que se rindió en 2017." },
  { id: 188, text: "El EFIP es básicamente un CAPTCHA humano para detectar si vos hiciste la carrera." },
  { id: 189, text: "La plomería tiene menos glamour, sí. Pero también menos entrevistas técnicas con gente mirando tu sufrimiento.", sprites: ["Plomero.png"] },
  { id: 190, text: "Vibecoding: ideal para prototipos, peligroso para producción, perfecto para justificar no saber programar." },
  { id: 191, text: "No le temas al indú. Temele al repositorio vacío con tu nombre." },
  { id: 192, text: "Siglo 21 no es mala, solo decidió que la pedagogía era opcional." },
  { id: 193, text: "No hay preguntero. Hay preguntas. Distinto, traumático y educativo." },
  { id: 194, text: "Tu futuro en IT depende de practicar. Tu pasado en IT depende de prompts." },
  { id: 195, text: "La plomería enseña una verdad: si algo se tapa, no sirve. Como tu aprendizaje antes del EFIP.", sprites: ["Plomero.png"] },
  { id: 196, text: "No estás estudiando online. Estás haciendo arqueología de PDFs." },
  { id: 197, text: "Un buen dev remoto no te roba el trabajo. Te recuerda que el trabajo exige saber." },
  { id: 198, text: "Vibecoding con Siglo 21 es coherente: ambos confían mucho en que el alumno rellene los huecos." },
  { id: 199, text: "Tu CV necesita proyectos. No capturas. No PDFs. Proyectos." },
  { id: 200, text: "Ánimo: todavía podés pasar de ‘usuario avanzado de IA’ a ‘persona que entiende lo que entrega’." },
  { id: 201, text: "Abriste Canvas y no Daypo. Pequeño paso para vos, enorme paso para tu integridad académica." },
  { id: 202, text: "La plomería paga más porque nadie dice ‘soy full stack de caños’ después de mirar dos tutoriales.", sprites: ["Plomero.png"] },
  { id: 203, text: "Siglo 21 te enseña a sobrevivir sin clases. El mercado te enseñará a sobrevivir sin respuestas multiple choice." },
  { id: 204, text: "El vibecoding no reemplaza fundamentos. Pero suena mejor que ‘no sé qué estoy haciendo’." },
  { id: 205, text: "Si te reemplazan, no será por globalización. Será por alguien que sí sabe declarar variables con nombres decentes." },
  { id: 206, text: "Tu carrera está en modo difícil: universidad virtual, PDFs sueltos y vos creyendo que estudiar es abrir pestañas." },
  { id: 207, text: "La IA hizo tus TPs. Ahora vos tenés que hacer de estudiante. Qué giro argumental." },
  { id: 208, text: "La plomería tiene herramientas físicas. Vos tenés frameworks que ni instalaste bien.", sprites: ["Plomero.png"] },
  { id: 209, text: "Siglo 21: donde la clase es un concepto filosófico y Canvas es el templo del desconcierto." },
  { id: 210, text: "No estás condenado laboralmente. Solo tenés un backlog de habilidades básicas." },
  { id: 211, text: "Vibecoding: cuando el roadmap es ‘que Dios y Copilot decidan’." },
  { id: 212, text: "Un contractor remoto entrega en dólares. Vos entregás en PDF con portada bonita." },
  { id: 213, text: "Toca practicar entrevistas técnicas. Primera pregunta: ‘¿Qué hiciste vos?’. Silencio dramático." },
  { id: 214, text: "El EFIP no odia a los alumnos. Solo odia los atajos, así que entiendo tu preocupación." },
  { id: 215, text: "La plomería no tiene saturación de juniors porque nadie dice ‘hice un bootcamp de cañerías de tres semanas’.", sprites: ["Plomero.png"] },
  { id: 216, text: "Tu formación universitaria parece microservicios: todo separado, nada conectado y nadie sabe dónde está la documentación." },
  { id: 217, text: "No sos un fraude. Sos una demo con funcionalidades prometidas." },
  { id: 218, text: "Canvas volvió a cargar. Más estabilidad que tu plan de estudio." },
  { id: 219, text: "Siglo 21 te dio PDFs sueltos para que aprendas. Vos los trataste como decoración académica." },
  { id: 220, text: "Vibecoding está bien para empezar. El problema es quedarse ahí y llamarlo seniority." },
  { id: 221, text: "La IA puede generar código. Vos todavía podés generar responsabilidad. Probemos." },
  { id: 222, text: "La plomería paga más porque el cliente sabe cuándo quedó arreglado. En software todos fingen hasta el próximo sprint.", sprites: ["Plomero.png"] },
  { id: 223, text: "No te reemplaza un extranjero. Te reemplaza la versión disciplinada de cualquier persona con internet." },
  { id: 224, text: "Siglo 21: educación a distancia, distancia entre el alumno y el contenido, distancia entre la cuota y la experiencia." },
  { id: 225, text: "Tu stack emocional tiene dependencias vulnerables: pánico, procrastinación y ‘mañana arranco’." },
  { id: 226, text: "No vale vibecoding. Hay que escribir código con intención, esa vieja tecnología." },
  { id: 227, text: "La saturación IT no perdona. Menos a quienes creen que public static void main es un hechizo." },
  { id: 228, text: "Daypo fue tu copiloto. El EFIP es turbulencia sin piloto automático." },
  { id: 229, text: "La plomería tiene caudal. Tu aprendizaje tiene goteo.", sprites: ["Plomero.png"] },
  { id: 230, text: "Siglo 21 no te abandonó. Te dejó en modo exploración libre sin tutorial." },
  { id: 231, text: "Un indu cobra menos que un senior local y sabe más que un junior improvisado. Qué feo triángulo amoroso." },
  { id: 232, text: "Vibecoding: excelente para decir ‘lo hice rápido’, peligroso cuando alguien pregunta ‘¿por qué?’." },
  { id: 233, text: "Tu CV dice ‘aprendizaje autónomo’. Traducción: ‘me pasaron PDFs y sobreviví como pude’." },
  { id: 234, text: "La IA no es tu enemiga. Tu enemiga es la pregunta ‘explicame tu solución’." },
  { id: 235, text: "La plomería no requiere Git, pero al menos si rompés algo, se inunda una habitación y no toda producción.", sprites: ["Plomero.png"] },
  { id: 236, text: "Siglo 21 te enseñó resiliencia, especialmente la resiliencia de pagar y autoconvencerte." },
  { id: 237, text: "Toca estudiar arquitectura de software. No, apilar prompts no es arquitectura." },
  { id: 238, text: "Si el mercado IT está saturado, imaginate el submercado de ‘hice TPs con IA y sé HTML básico’." },
  { id: 239, text: "Canvas tiene módulos. Vos tenés excusas modularizadas." },
  { id: 240, text: "Vibecoding es divertido hasta que el bug también tiene buenas vibras y no se va." },
  { id: 241, text: "La plomería paga más porque no podés arreglar una pérdida copiando de Studocu.", sprites: ["Plomero.png"] },
  { id: 242, text: "Un buen contractor remoto no te reemplaza por barato, te reemplaza por confiable. Terrible concepto." },
  { id: 243, text: "Siglo 21: donde el contenido se entrega como si fueran pistas de un escape room académico." },
  { id: 244, text: "El EFIP no quiere que memorices. Quiere que entiendas. Sí, ya sé, nadie avisó." },
  { id: 245, text: "Tu carrera parece un repositorio sin README: existe, pero entrar da miedo." },
  { id: 246, text: "La IA puede hacer tus TPs, pero no puede transpirar por vos en una entrevista." },
  { id: 247, text: "La plomería tiene presión. Tu cursada también, pero solo cerca del parcial.", sprites: ["Plomero.png"] },
  { id: 248, text: "Vibecoding con café y ansiedad no es productividad, es autoengañarse." },
  { id: 249, text: "Siglo 21 te da recursos. Algunos incluso están relacionados con la materia." },
  { id: 250, text: "No estás fuera del mercado laboral. Estás en la cola, atrás de gente con proyectos, inglés y menos negación." },
  { id: 251, text: "No vamos a copiar. Vamos a comprender. Traje casco por si te explota la costumbre." },
  { id: 252, text: "Un contractor remoto te reemplaza mientras dormís. Vos también dormís, pero sobre los PDFs." },
  { id: 253, text: "La plomería paga más porque el oficio resuelve problemas reales. Tu código todavía está resolviendo cómo ejecutarse.", sprites: ["Plomero.png"] },
  { id: 254, text: "Vibecoding: cuando programar se vuelve terapia alternativa y el bug necesita sahumerio." },
  { id: 255, text: "Siglo 21: la universidad donde el silencio pedagógico también cuenta como experiencia inmersiva." },
  { id: 256, text: "Tu mejor herramienta era la IA. Ahora tu mejor herramienta debería ser una silla, una hora y estudiar." },
  { id: 257, text: "El EFIP es un pull request a tu cerebro. Ojalá no tenga conflictos." },
  { id: 258, text: "La saturación de IT no es el problema. El problema es diferenciarte con ‘sé usar Google’." },
  { id: 259, text: "Canvas es tu aula. El PDF es tu docente. La desesperación, tu tutora." },
  { id: 260, text: "La plomería no tiene standups diarios. Otro punto para la plomería.", sprites: ["Plomero.png"] },
  { id: 261, text: "No te reemplaza la IA, te reemplaza alguien que depura antes de entregar." },
  { id: 262, text: "Vibecoding es el nombre elegante de ‘que salga lo que salga’." },
  { id: 263, text: "Siglo 21 no bajó la vara. La convirtió en archivo descargable." },
  { id: 264, text: "Tu perfil junior necesita práctica, no más certificados con diseños bonitos." },
  { id: 265, text: "Daypo te enseñó a elegir. El mercado laboral te pide construir. Injustísimo." },
  { id: 266, text: "Un contractor global abre el repo. Vos abrís Canvas y ya te cansás." },
  { id: 267, text: "La plomería tiene sindicatos, oficios y demanda. Vos tenés ‘conocimientos básicos de Python’ en el CV.", sprites: ["Plomero.png"] },
  { id: 268, text: "Vibecoding: perfecto hasta que aparece mantenimiento, ese villano clásico." },
  { id: 269, text: "Siglo 21: donde la clase grabada es más rara que un TP sin IA." },
  { id: 270, text: "No estás perdido. Estás sin mapa, sin brújula y con diez PDFs llamados ‘material complementario’." },
  { id: 271, text: "La IA no debería hacer tus tareas. Debería hacerte preguntas incómodas sobre ellas." },
  { id: 272, text: "El outsourcing global no es amenaza; es recordatorio de que internet también distribuye competencia." },
  { id: 273, text: "La plomería tiene menos glamour que software, pero el agua no cambia de framework cada seis meses.", sprites: ["Plomero.png"] },
  { id: 274, text: "Vibecoding no es malo. Malo es venderlo como ingeniería." },
  { id: 275, text: "Siglo 21 te preparó para trabajar remoto: nadie te ve, nadie te explica, todo vence igual." },
  { id: 276, text: "Tu código tiene olor a prompt recién copiado." },
  { id: 277, text: "El EFIP no se puede aprobar con screenshots de confianza." },
  { id: 278, text: "Un contractor remoto no necesita robarte el trabajo. Vos se lo dejás en bandeja con variables llamadas cosa1." },
  { id: 279, text: "La plomería paga más porque cuando decís ‘sé conectar cosas’, lo demostrós sin PowerPoint.", sprites: ["Plomero.png"] },
  { id: 280, text: "Canvas te mira. Sabe que descargaste el PDF y nunca volviste." },
  { id: 281, text: "Vibecoding es como estudiar por pregunteros: puede funcionar una vez, pero no construye alma." },
  { id: 282, text: "Siglo 21: donde el alumno aprende a autogestionarse o a volverse experto en excusas." },
  { id: 283, text: "La saturación de juniors no sería tan grave si todos no tuvieran el mismo portfolio de calculadora y CRUD." },
  { id: 284, text: "La IA hizo el CRUD. Vos hiciste la portada. Trabajo en equipo moderno." },
  { id: 285, text: "La plomería no necesita Scrum. Qué avance civilizatorio.", sprites: ["Plomero.png"] },
  { id: 286, text: "Un buen dev remoto cobra por resolver. Vos todavía estás en la fase de ‘descubrir qué era la consigna’." },
  { id: 287, text: "Vibecoding: el arte de generar deuda técnica con confianza." },
  { id: 288, text: "Siglo 21 no tiene mala pedagogía, tiene pedagogía invisible. Muy invisible." },
  { id: 289, text: "Vamos a estudiar patrones de diseño. Tu patrón favorito sigue siendo ‘entregar tarde con IA’." },
  { id: 290, text: "El EFIP es el momento en que la carrera pregunta: ‘¿estabas presente o solo conectado?’." },
  { id: 291, text: "La plomería tiene herramientas caras, pero ninguna tan cara como una carrera que usaste para aprender a buscar resúmenes.", sprites: ["Plomero.png"] },
  { id: 292, text: "No te preocupes por el futuro laboral. Preocupate por el presente simple de explicar un if." },
  { id: 293, text: "Un contractor remoto puede estar a doce husos horarios y aun así llegar antes que vos a entender la consigna." },
  { id: 294, text: "Vibecoding sin fundamentos es como Siglo 21 sin PDFs: bueno, no queda casi nada." },
  { id: 295, text: "Canvas es la mazmorra, los PDFs son enemigos comunes y el EFIP es el jefe final que no se derrota con Studocu." },
  { id: 296, text: "La IA puede escribir código limpio. Vos podés empezar por limpiar tu carpeta de ‘TP final final definitivo posta’." },
  { id: 297, text: "La plomería paga más porque el mercado valora gente que arregla cosas. En teoría, eso también aplicaba a Informática.", sprites: ["Plomero.png"] },
  { id: 298, text: "Siglo 21 te entrenó para la incertidumbre. También para buscar material como si fueras detective privado." },
  { id: 299, text: "Vibecoding, outsourcing, IA, saturación… todas amenazas reales. Pero ninguna tan peligrosa como tu hábito de no practicar." },
  { id: 300, text: "Ánimo. Todavía podés convertir esta carrera de ‘PDFs, prompts y culpa’ en algo parecido a una profesión." },
];
